-- Taxas importadas da planilha TAXA ENTREGA - Petrolina e Juazeiro (1).xlsx.
-- Cada guia atualiza somente a unidade correspondente; linhas sem preco foram preservadas.
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Água Bela',10.4,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Alagadiço',9.5,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Alto da Aliança',12.4,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Alto da Maravilha',10.2,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Alto do Alencar',11.9,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Alto do Cruzeiro',11.3,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Angary',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Antônio Conselheiro',12.4,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Antonio Guilhermino',16.4,2800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Argemiro',12,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Cajueiro',10.3,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Castelo Branco',13,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Centenário',10.5,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Centro',9.1,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Coréia',10,1600,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Country Club',11.3,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Distrito Industrial',14.3,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Dom José Rodrigues',15.3,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Dom Tomaz',13.1,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Expedito de Almeida Nascimento',10.8,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Itaberaba',13.9,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Jardim Flórida',10.5,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Jardim Novo Encontro',11.1,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Jardim Primavera',21.7,3550,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Jardim São Paulo',12.5,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Jardim Universitário',10.7,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Jardim Vitória',9.8,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','João Paulo II',17.1,2950,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','João XXIII',10.5,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Lomanto Júnior',11.2,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Malhada da Areia',12.6,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Maringá',9.7,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Matatu',10.3,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Monte Castelo',12.5,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Mussambê',9.2,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Nossa Senhora da Penha',10,1600,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Nossa Senhora das Grotas',11.9,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Nova Esperança',12.3,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Nova Juazeiro',14.8,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Padre Vicente',11.7,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Palmares',11.6,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Parque Centenário',11.7,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Parque Residencial',18,2950,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Pedra do Lord',12,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Pedro Raimundo',15.7,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Piranga',10.8,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Piranga I',11.8,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Piranga II',12.9,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Quidé',11.8,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Santa Maria Goretti',10.2,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Santo Antônio',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','São Geraldo',11.4,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Sol Levante',15.3,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Tabuleiro',15.5,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Tancredo Neves',12.8,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Usina Aliança',12,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Vila Nova Fé',16.2,2800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Juazeiro','Vila Tiradentes',12.7,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Alto do Cocar',6.1,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Antônio Cassimiro',8.5,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Areia Branca',9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Atrás da Banca',6.8,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Boa Esperança',14.4,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Caminho do Sol',8,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Carneiro',14.1,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Centro',9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Cidade Universitária',10.1,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','COHAB Massangano',1.5,700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Cohab São Francisco',2.2,800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Cohab 6',1.7,700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Colônia Imperial',9.6,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Cosme e Damião',3.2,900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Distrito Industrial',4.5,1000,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Dom Avelar',11.5,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Dona Alexandrina',10.9,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Fernando Idalino',12.1,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Gercino Coelho',6,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Henrique Leite',12.3,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Jardim Amazonas',4.7,1000,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Jardim Maravilha',5.1,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Jardim Petrópolis',1.9,700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Jardim São Paulo',3,800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Jatobá',12.6,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','João de Deus',5.2,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','José e Maria',8.7,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','KM 2',6.6,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Loteamento Recife',9.8,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Maria Auxiliadora',8.8,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Ouro Preto',5.7,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Palhinhas',5.9,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Pedra do Bode',11.6,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Pedra Linda',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Pedro Raimundo',5.3,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Portal da Cidade',1.7,700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Rio Claro',1.1,700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Rio Corrente',1.1,700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','São José',9.2,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Terra do Sul',10.3,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Topázio',11.9,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Vale Grande Rio',5.4,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Vila dos Ingás',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Vila Eduardo',9.3,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Vila Eulália',7.5,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('sao-goncalo','Petrolina','Vila Mocó',6.6,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Água Bela',12.8,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Alagadiço',11.9,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Alto da Aliança',14.8,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Alto da Maravilha',12.6,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Alto do Alencar',14.3,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Alto do Cruzeiro',13.8,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Angary',11.3,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Antônio Conselheiro',14.8,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Antonio Guilhermino',18.8,3100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Argemiro',14.4,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Cajueiro',12.7,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Castelo Branco',15.4,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Centenário',12.9,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Centro',11.5,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Coréia',12.4,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Country Club',13.7,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Distrito Industrial',16.7,2800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Dom José Rodrigues',17.7,2950,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Dom Tomaz',15.5,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Expedito de Almeida Nascimento',13.2,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Itaberaba',16.3,2800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Jardim Flórida',12.9,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Jardim Novo Encontro',13.6,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Jardim Primavera',24.1,4000,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Jardim São Paulo',14.9,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Jardim Universitário',13.1,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Jardim Vitória',12.2,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','João Paulo II',19.5,3250,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','João XXIII',12.9,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Lomanto Júnior',13.6,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Malhada da Areia',15,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Maringá',12.1,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Matatu',12.7,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Monte Castelo',14.9,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Mussambê',11.6,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Nossa Senhora da Penha',12.4,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Nossa Senhora das Grotas',14.3,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Nova Esperança',14.7,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Nova Juazeiro',17.2,2950,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Padre Vicente',14.1,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Palmares',14,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Parque Centenário',14.1,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Parque Residencial',20.4,3400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Pedra do Lord',14.4,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Pedro Raimundo',18.1,3100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Piranga',13.2,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Piranga I',14.2,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Piranga II',15.3,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Quidé',14.2,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Santa Maria Goretti',12.6,1900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Santo Antônio',11.3,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','São Geraldo',13.8,2350,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Sol Levante',17.7,2950,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Tabuleiro',17.9,2950,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Tancredo Neves',15.2,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Usina Aliança',14.5,2500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Vila Nova Fé',18.6,3100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Juazeiro','Vila Tiradentes',15.2,2650,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Alto do Cocar',5.8,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Antônio Cassimiro',4,900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Areia Branca',5.4,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Atrás da Banca',8.8,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Boa Esperança',5.9,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Caminho do Sol',5.5,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Carneiro',9.1,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Centro',7,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Cidade Universitária',6.6,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','COHAB Massangano',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Cohab São Francisco',11,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Cohab 6',11.2,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Colônia Imperial',6.4,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Cosme e Damião',9.1,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Distrito Industrial',11.7,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Dona Alexandrina',3.2,900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Fernando Idalino',7.5,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Gercino Coelho',8,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Henrique Leite',7.6,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Jardim Amazonas',6.8,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Jardim Maravilha',8,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Jardim Petrópolis',12,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Jardim São Paulo',9.1,1500,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Jatobá',7.9,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','João de Deus',6.5,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','José e Maria',2.8,800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','KM 2',7.2,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Loteamento Recife',3.4,900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Maria Auxiliadora',5.7,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Ouro Preto',5.8,1100,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Palhinhas',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Pedra do Bode',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Pedra Linda',4.4,1000,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Pedro Raimundo',6.7,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Portal da Cidade',8.9,1400,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Rio Claro',11.1,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Rio Corrente',11.2,1800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','São Gonçalo',10.6,1700,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','São José',6.2,1200,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Terra do Sul',2.8,800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Topázio',2.6,800,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Vale Grande Rio',7.2,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Vila dos Ingás',7.5,1300,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Vila Eduardo',4.6,1000,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Vila Eulália',3.1,900,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO branch_neighborhood_fees (branch_id,city,neighborhood,distance_km,fee_cents,updated_at) VALUES ('dom-avelar','Petrolina','Vila Mocó',7.3,1300,CURRENT_TIMESTAMP);
