/* Pagamentos do caixa e acabamentos finais dos cartões de pedido. */
const blissFinalOrderCard=orderCard;
orderCard=order=>{
  const withoutDuplicateDelete=blissFinalOrderCard(order).replace(/<button\b[^>]*data-delete-order="[^"]*"[^>]*>Excluir<\/button>/g,"");
  return withoutDuplicateDelete.replace('</div><span class="order-card-hint">',`<button class="danger-btn compact" data-delete-order="${esc(order.id)}">Excluir</button></div><span class="order-card-hint">`);
};

function cashierCents(value){return Math.max(0,Math.round(Number(String(value||"").replace(/[^0-9,.-]/g,"").replace(/\./g,"").replace(",","."))*100)||0)}
function cashierMoneyInput(cents){return (Math.max(0,Number(cents)||0)/100).toFixed(2).replace(".",",")}

async function openCashierPayment(id){
  const cashier=state.cashier,order=cashier.orders.find(item=>item.id===id);if(!order)return;
  if(!cashier.employees){try{cashier.employees=(await api('/api/cashier/employees')).employees||[]}catch{cashier.employees=[]}}
  if(order.payment_status!=="aberto"){
    api(`/api/cashier/orders/${encodeURIComponent(id)}/payment`,{method:"PATCH",body:JSON.stringify({payment_status:"aberto"})}).then(async()=>{await refreshCashier();renderCashierPanel();toast("Pagamento reaberto")}).catch(error=>toast(error.message));
    return;
  }
  const grossTotal=Math.max(0,Number(order.total_cents||0));
  const employeePercent=Math.max(0,Math.min(100,Number(cashier.catalog?.settings?.employee_discount_percent||0)));
  const methods=`<option value="dinheiro">Dinheiro</option><option value="pix">Pix</option><option value="credito">Cartão de crédito</option><option value="debito">Cartão de débito</option><option value="folha">Debitar em folha</option>`;
  const selected=["dinheiro","pix","credito","debito"].includes(order.payment_method)?order.payment_method:"dinheiro";
  const row=(method=selected,amount=grossTotal)=>`<div class="cashier-payment-row"><select class="cashier-payment-method">${methods}</select><input class="cashier-payment-amount" inputmode="decimal" value="${cashierMoneyInput(amount)}" aria-label="Valor da forma de pagamento"><button type="button" class="icon-btn cashier-remove-payment" aria-label="Remover forma">×</button></div>`;
  layer(`<div class="drawer-header"><button class="icon-btn" data-close>×</button><div><h2>Receber pagamento</h2><span class="muted">Pedido ${esc(order.id)} • total ${money(grossTotal)}</span></div></div><div class="drawer-content cashier-payment-dialog"><div class="detail-totals"><div><span>Total dos itens</span><strong>${money(grossTotal)}</strong></div><div id="cashier-discount-row" class="hidden"><span>Desconto</span><strong id="cashier-discount-value">${money(0)}</strong></div><div class="detail-grand-total"><span>Total a receber</span><strong id="cashier-payment-total">${money(grossTotal)}</strong></div></div><label class="check-row"><input type="checkbox" id="cashier-employee-discount"><span><strong>Cliente é funcionário</strong><small>Desmarcado por padrão. Aplica ${employeePercent}% configurado pelo proprietário.</small></span></label><div class="field hidden" id="cashier-employee-row"><label>Funcionário</label><select id="cashier-employee-id"><option value="">Selecione o funcionário</option>${cashier.employees.map(employee=>`<option value="${employee.id}">${esc(employee.name)}</option>`).join('')}</select></div><div class="settings-grid"><div class="field"><label>Desconto manual</label><select id="cashier-discount-mode"><option value="">Sem desconto</option><option value="percent">Por porcentagem</option><option value="amount">Em reais</option></select></div><div class="field hidden" id="cashier-discount-input-row"><label id="cashier-discount-input-label">Valor</label><input id="cashier-discount-input" inputmode="decimal" placeholder="0,00"></div></div><p class="muted">Informe uma ou mais formas. A soma precisa ser igual ao total com desconto.</p><div id="cashier-payment-rows">${row()}</div><button type="button" class="secondary-btn compact" id="cashier-add-payment">＋ Adicionar forma de pagamento</button><div class="detail-totals"><div><span>Falta distribuir</span><strong id="cashier-payment-remaining">${money(0)}</strong></div></div><div class="field hidden" id="cashier-cash-row"><label>Valor entregue em dinheiro <small>(opcional)</small></label><input id="cashier-cash-received" inputmode="decimal" placeholder="Deixe em branco para valor exato"><small id="cashier-change-preview">Em branco, considera valor exato • troco: ${money(0)}</small></div></div><div class="drawer-footer"><button class="primary-btn full" id="cashier-confirm-payment">Confirmar pagamento</button></div>`,`drawer admin-order-drawer`);
  document.querySelector("[data-close]").onclick=closeLayer;
  const rows=$("#cashier-payment-rows"),remaining=$("#cashier-payment-remaining"),cashRow=$("#cashier-cash-row"),cashReceived=$("#cashier-cash-received"),changePreview=$("#cashier-change-preview"),employee=$("#cashier-employee-discount"),employeeRow=$("#cashier-employee-row"),employeeId=$("#cashier-employee-id"),discountMode=$("#cashier-discount-mode"),discountInput=$("#cashier-discount-input"),discountInputRow=$("#cashier-discount-input-row"),discountInputLabel=$("#cashier-discount-input-label"),discountRow=$("#cashier-discount-row"),discountValue=$("#cashier-discount-value"),totalValue=$("#cashier-payment-total");
  const payments=()=>Array.from(rows.querySelectorAll(".cashier-payment-row")).map(item=>({method:item.querySelector("select").value,amount_cents:cashierCents(item.querySelector("input").value)}));
  const wireRow=item=>{const select=item.querySelector("select"),input=item.querySelector("input"),remove=item.querySelector("button");select.value=select.value||selected;select.onchange=refresh;input.oninput=refresh;remove.onclick=()=>{if(rows.children.length===1)return toast("Mantenha ao menos uma forma de pagamento.");item.remove();refresh()}};
  const discount=()=>{if(employee.checked)return Math.round(grossTotal*employeePercent/100);if(discountMode.value==="percent")return Math.round(grossTotal*Math.max(0,Math.min(100,Number(String(discountInput.value||"").replace(",","."))||0))/100);return discountMode.value==="amount"?Math.min(grossTotal,cashierCents(discountInput.value)):0};
  const total=()=>Math.max(0,grossTotal-discount());
  const refresh=(syncSingle=false)=>{const due=total();if(syncSingle&&rows.children.length===1)rows.querySelector(".cashier-payment-amount").value=cashierMoneyInput(due);const list=payments(),paid=list.reduce((sum,item)=>sum+item.amount_cents,0),difference=due-paid,cashDue=list.filter(item=>item.method==="dinheiro").reduce((sum,item)=>sum+item.amount_cents,0),typed=String(cashReceived.value||"").trim(),received=typed?cashierCents(typed):cashDue;employeeRow.classList.toggle("hidden",!employee.checked);discountInputRow.classList.toggle("hidden",employee.checked||!discountMode.value);discountMode.disabled=employee.checked;discountInputLabel.textContent=discountMode.value==="percent"?"Desconto (%)":"Desconto (R$)";discountRow.classList.toggle("hidden",!discount());discountValue.textContent=money(discount());totalValue.textContent=money(due);remaining.textContent=money(Math.abs(difference));remaining.parentElement.querySelector("span").textContent=difference<0?"Valor excedente":"Falta distribuir";cashRow.classList.toggle("hidden",!cashDue);changePreview.textContent=typed?`Troco: ${money(Math.max(0,received-cashDue))}`:`Em branco, considera valor exato • troco: ${money(0)}`;};
  rows.querySelectorAll(".cashier-payment-row").forEach(wireRow);$("#cashier-add-payment").onclick=()=>{if(rows.children.length>=4)return toast("Use no máximo quatro formas de pagamento.");rows.insertAdjacentHTML("beforeend",row("pix",0));wireRow(rows.lastElementChild);refresh()};cashReceived.oninput=refresh;employee.onchange=()=>refresh(true);discountMode.onchange=()=>refresh(true);discountInput.oninput=()=>refresh(true);refresh();
  $("#cashier-confirm-payment").onclick=async()=>{const button=$("#cashier-confirm-payment"),list=payments(),sum=list.reduce((value,item)=>value+item.amount_cents,0),cashDue=list.filter(item=>item.method==="dinheiro").reduce((value,item)=>value+item.amount_cents,0),typed=String(cashReceived.value||"").trim(),received=typed?cashierCents(typed):cashDue;if(employee.checked&&!employeeId.value)return toast("Selecione o funcionário.");if(!employee.checked&&list.some(item=>item.method==='folha'))return toast("Débito em folha só pode ser usado para funcionário.");if(!list.every(item=>item.amount_cents>0)||sum!==total())return toast("Distribua exatamente o total com desconto entre as formas de pagamento.");if(cashDue&&received<cashDue)return toast("O valor informado deve ser igual ou maior que a parte em dinheiro.");button.disabled=true;try{const result=await api(`/api/cashier/orders/${encodeURIComponent(id)}/payment`,{method:"PATCH",body:JSON.stringify({payment_status:"pago",payment_method:list[0].method,payments:list,cash_received_cents:cashDue?received:null,employee_discount:employee.checked,employee_id:employeeId.value,discount_mode:discountMode.value,discount_percent:discountMode.value==="percent"?Number(String(discountInput.value||"").replace(",","."))||0:0,discount_amount_cents:discountMode.value==="amount"?cashierCents(discountInput.value):0})});await refreshCashier();closeLayer();renderCashierPanel();toast(result.change_for_cents?`Pagamento confirmado • troco ${money(result.change_for_cents)}`:"Pagamento confirmado")}catch(error){toast(error.message);button.disabled=false}};
}

document.addEventListener("click",event=>{const button=event.target.closest("[data-cashier-payment]");if(!button)return;event.preventDefault();event.stopPropagation();openCashierPayment(button.dataset.cashierPayment)},true);

// No painel do proprietário, dinheiro sem valor informado significa pagamento exato.
// Mantemos a digitação apenas para os casos em que há troco.
queueMicrotask(()=>{const previousOwnerSettlement=openPaymentSettlement;openPaymentSettlement=id=>{previousOwnerSettlement(id);queueMicrotask(()=>{const input=$("#cash-received"),confirm=$("#confirm-payment"),method=$("#settlement-method"),total=$("#settlement-total");if(!input||!confirm||!method||!total)return;input.required=false;input.placeholder="Deixe em branco para valor exato";const label=input.closest(".field")?.querySelector("label");if(label)label.innerHTML="Valor recebido do cliente <small>(opcional)</small>";confirm.addEventListener("click",()=>{const split=$("#split-payment-enabled")?.checked;if(method.value!=="dinheiro"||split||String(input.value||"").trim())return;input.value=String(total.textContent||"").replace(/[^0-9,.-]/g,"").trim();input.dispatchEvent(new Event("input",{bubbles:true}))},true)})}});
