/* Central de integrações: conexões técnicas ficam fora das configurações gerais. */
const integrationsNav=adminNavButtons;
adminNavButtons=function(){
  return integrationsNav().replace(/(<button[^>]+data-admin-view="settings"[\s\S]*?<\/button>)/,`<button class="${state.admin.view==="integrations"?"active":""}" data-admin-view="integrations"><span class="admin-nav-icon">⌁</span><span class="nav-full">Integrações</span><span class="nav-short">Conexões</span></button>$1`);
};

function integrationPill(ready,label){return `<span class="connection-pill ${ready?"ready":""}">${ready?"Configurado":label||"Aguardando dados"}</span>`}
function integrationGuide(title,items){return `<div class="integration-guide"><strong>${title}</strong><ol>${items.map(item=>`<li>${item}</li>`).join("")}</ol></div>`}
function integrationsView(){
  const s=state.catalog.settings||{},p=state.admin.printStatus||{},scale=state.admin.integrationStatus?.scale||{},origin=location.origin;
  const webhook=`${origin}/api/integrations/pedeai/webhook`,scaleUrl=`${origin}/api/scale/weight`;
  return `<form id="integrations-form" class="settings-stack integrations-stack">
    <section class="panel integration-panel"><div class="panel-head"><div><h2>Balança Prix 3 Toledo</h2><span class="muted">Self-service por peso, enviado do computador do caixa para o PDV.</span></div>${integrationPill(Boolean(scale.configured),"Agente local necessário")}</div>
      <div class="integration-status-grid"><div><span>Última leitura</span><strong>${scale.grams?`${(Number(scale.grams)/1000).toLocaleString("pt-BR",{minimumFractionDigits:3,maximumFractionDigits:3})} kg`:"Nenhuma leitura"}</strong><small>${scale.captured_at?`Recebida em ${esc(String(scale.captured_at).replace("T"," ").replace("Z",""))}`:"Coloque o produto na balança e use “Ler balança” no Balcão."}</small></div><div><span>Preço configurado</span><strong>${money(Number(s.self_service_price_per_kg_cents||3000))}/kg</strong><small>Edite abaixo e salve as integrações.</small></div></div>
      <div class="settings-grid"><div class="field"><label>Preço do self-service por kg (R$)</label><input name="self_service_price_per_kg" inputmode="decimal" required value="${(Number(s.self_service_price_per_kg_cents||3000)/100).toFixed(2).replace('.',',')}"><small>Ex.: 30,00 para cobrar R$ 30,00 por kg.</small></div></div>
      <div class="settings-grid"><div class="field wide"><label>URL para o agente local</label><div class="field-action"><input readonly value="${esc(scaleUrl)}"><button type="button" class="secondary-btn" data-copy-integration="${esc(scaleUrl)}">Copiar</button></div><small>Agente pronto configurado para a USB-SERIAL CH340 (COM4, 9600 bps, 8N1 e fluxo por hardware).</small></div><div class="field wide"><label>Token do agente</label><div class="field-action"><input id="scale-token-output" readonly value="" placeholder="Gere um token exclusivo para este computador"><button type="button" class="secondary-btn" id="generate-scale-token">Gerar token</button></div><small>O token só é exibido ao gerar. Ao criar outro, o anterior deixa de funcionar.</small></div></div>
      ${integrationGuide("Para conectar",["No computador da balança, execute o instalador pronto da Bliss.","O arquivo de configuração já recebe a URL e o token deste computador.","Confirme no Windows: USB-SERIAL CH340 (COM4), 9600 bps, 8 bits, sem paridade, 1 stop bit e controle de fluxo por hardware. Depois, faça uma pesagem de teste."])}
    </section>
    <section class="panel integration-panel"><div class="panel-head"><div><h2>Impressoras</h2><span class="muted">Comandas do caixa e cozinha usando o conector local do Windows.</span></div>${integrationPill(Boolean(p.configured||s.print_bridge_configured),"Conector não configurado")}</div>
      <div class="settings-grid"><div class="field"><label>Impressora do caixa</label><input name="reception_printer" value="${esc(s.reception_printer||"")}" placeholder="Ex.: EPSON TM-T20X Receipt"></div><div class="field"><label>Impressora da cozinha</label><input name="kitchen_printer" value="${esc(s.kitchen_printer||"")}" placeholder="Ex.: ELGIN i9 Cozinha"></div><div class="field key-field"><label>Chave do conector</label><div class="field-action"><input name="print_bridge_key" type="password" autocomplete="new-password" placeholder="${s.print_bridge_configured?"Chave já salva — preencha apenas para trocar":"Gere uma chave segura"}"><button class="secondary-btn" type="button" id="generate-integration-print-key">Gerar</button></div></div><div class="field"><label>Vias por impressão</label><input name="print_copies" type="number" min="1" max="5" value="${Math.max(1,Number(s.print_copies||1))}"></div></div>
      <label class="check-row pedeai-enable"><input type="checkbox" name="auto_print_enabled" ${s.auto_print_enabled?"checked":""}><span><strong>Imprimir pedidos automaticamente</strong><small>${Number(p.pending||0)} na fila • ${Number(p.printed||0)} concluídas.</small></span></label>
      <div class="print-actions"><button type="button" class="secondary-btn" id="download-integration-bridge">Baixar conector para Windows</button></div>
      ${integrationGuide("Para conectar",["Instale e teste as impressoras no Windows.","Copie os nomes exatamente como aparecem no Windows, gere a chave e salve.","Baixe o conector, informe a chave nele e mantenha-o aberto no computador do caixa."])}
    </section>
    <section class="panel integration-panel"><div class="panel-head"><div><h2>PedeAI</h2><span class="muted">Pedidos entrarão no painel como Delivery (PedeAI) após a homologação.</span></div>${integrationPill(Boolean(s.pedeai_api_token_configured&&s.pedeai_store_id),"Pré-configuração")}</div>
      <div class="settings-grid"><div class="field"><label>Ambiente</label><select name="pedeai_environment"><option value="sandbox" ${s.pedeai_environment!=="production"?"selected":""}>Sandbox / homologação</option><option value="production" ${s.pedeai_environment==="production"?"selected":""}>Produção</option></select></div><div class="field"><label>ID da loja</label><input name="pedeai_store_id" maxlength="160" value="${esc(s.pedeai_store_id||"")}" placeholder="Informado pelo PedeAI"></div><div class="field"><label>Client ID / App ID</label><input name="pedeai_client_id" maxlength="160" value="${esc(s.pedeai_client_id||"")}" placeholder="Informado pelo PedeAI"></div><div class="field"><label>URL base da API</label><input name="pedeai_api_base_url" type="url" maxlength="300" value="${esc(s.pedeai_api_base_url||"")}" placeholder="https://... fornecida pelo PedeAI"></div><div class="field"><label>Token de acesso</label><input name="pedeai_api_token" type="password" autocomplete="new-password" placeholder="${s.pedeai_api_token_configured?"Token salvo — preencha apenas para trocar":"Cole o token fornecido pelo PedeAI"}"></div><div class="field"><label>Segredo do webhook</label><input name="pedeai_webhook_secret" type="password" autocomplete="new-password" placeholder="${s.pedeai_webhook_secret_configured?"Segredo salvo — preencha apenas para trocar":"Informe se o PedeAI fornecer"}"></div><div class="field wide"><label>URL de recebimento</label><div class="field-action"><input readonly value="${esc(webhook)}"><button type="button" class="secondary-btn" data-copy-integration="${esc(webhook)}">Copiar</button></div></div></div>
      <label class="check-row pedeai-enable"><input type="checkbox" name="pedeai_enabled" ${s.pedeai_enabled?"checked":""}><span><strong>Ativar recebimento PedeAI</strong><small>Use somente após a homologação aprovada pelo PedeAI.</small></span></label>
    </section>
    <section class="panel integration-panel marketplace-panel"><div class="panel-head"><div><h2>iFood</h2><span class="muted">Preparação para receber e atualizar pedidos do marketplace.</span></div>${integrationPill(false,"Aguardando API")}</div>
      <div class="integration-checklist"><label><input type="checkbox" disabled> Cadastro da loja ativo no iFood</label><label><input type="checkbox" disabled> Identificador da loja (merchant/store ID)</label><label><input type="checkbox" disabled> Credenciais de integração / autorização liberadas pelo iFood</label><label><input type="checkbox" disabled> Especificação do webhook e eventos de pedido</label><label><input type="checkbox" disabled> Catálogo e regras de status aprovados para sincronização</label></div>
      <p class="muted">Quando você receber o acesso técnico do iFood, cadastre aqui o identificador, método de autorização e URL de webhook. As credenciais só serão salvas no servidor após validarmos a documentação oficial.</p>
    </section>
    <section class="panel integration-panel marketplace-panel"><div class="panel-head"><div><h2>99Food</h2><span class="muted">Preparação para receber e atualizar pedidos do marketplace.</span></div>${integrationPill(false,"Aguardando API")}</div>
      <div class="integration-checklist"><label><input type="checkbox" disabled> Cadastro da loja ativo no 99Food</label><label><input type="checkbox" disabled> Identificador da loja / parceiro</label><label><input type="checkbox" disabled> Credenciais ou token concedidos pelo 99Food</label><label><input type="checkbox" disabled> Especificação de webhook e autenticação</label><label><input type="checkbox" disabled> Mapeamento de produtos e testes de pedido</label></div>
      <p class="muted">Quando receber o material técnico do 99Food, faremos o mapeamento de pedidos, status, cancelamentos e catálogo antes de habilitar produção.</p>
    </section>
    <div class="settings-save"><button class="primary-btn">Salvar integrações configuradas</button></div>
  </form>`;
}

const integrationRenderAdmin=renderAdmin;
renderAdmin=function(){if(state.admin.view==="integrations"){ $("#app").innerHTML=adminLayout(integrationsView(),"Integrações"); bindAdmin();bindIntegrations();return } integrationRenderAdmin()};
function bindIntegrations(){
  document.querySelectorAll("[data-copy-integration]").forEach(button=>button.onclick=async()=>{try{await navigator.clipboard.writeText(button.dataset.copyIntegration);toast("Endereço copiado")}catch{toast("Copie o endereço exibido no campo")}});
  $("#generate-integration-print-key").onclick=()=>{const bytes=crypto.getRandomValues(new Uint8Array(18));$("[name=print_bridge_key]").value=Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")};
  $("#generate-scale-token").onclick=async()=>{const button=$("#generate-scale-token");button.disabled=true;try{const result=await api("/api/admin/integrations/scale-token",{method:"POST"});$("#scale-token-output").value=result.token;await navigator.clipboard?.writeText(result.token);toast("Token gerado e copiado. Cole no agente da balança.")}catch(error){toast(error.message)}finally{button.disabled=false}};
  $("#download-integration-bridge").onclick=downloadPrintBridge;
  $("#integrations-form").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=form.querySelector(".primary-btn"),s=state.catalog.settings||{},price=Math.round(Number(String(data.get("self_service_price_per_kg")).replace(",","."))*100);if(!Number.isFinite(price)||price<=0)return toast("Informe um preço por kg válido");button.disabled=true;try{await api("/api/admin/settings",{method:"PATCH",body:JSON.stringify({reception_printer:data.get("reception_printer"),kitchen_printer:data.get("kitchen_printer"),print_bridge_key:data.get("print_bridge_key"),print_copies:Math.max(1,Math.min(5,Number(data.get("print_copies"))||1)),auto_print_enabled:form.elements.auto_print_enabled.checked,pedeai_enabled:form.elements.pedeai_enabled.checked,pedeai_environment:data.get("pedeai_environment"),pedeai_store_id:data.get("pedeai_store_id"),pedeai_client_id:data.get("pedeai_client_id"),pedeai_api_base_url:data.get("pedeai_api_base_url"),pedeai_api_token:data.get("pedeai_api_token"),pedeai_webhook_secret:data.get("pedeai_webhook_secret"),is_open:s.is_open,closing_time:s.closing_time,minimum_order_cents:s.minimum_order_cents,delivery_eta:s.delivery_eta,pickup_eta:s.pickup_eta,phone:s.phone,address:s.address,table_count:s.table_count,featured_product_limit:s.featured_product_limit,self_service_price_per_kg_cents:price,waiter_fee_enabled:s.waiter_fee_enabled,waiter_fee_percent:s.waiter_fee_percent,delivery_neighborhood_fees:s.delivery_neighborhood_fees,delivery_surcharge_enabled:s.delivery_surcharge_enabled,delivery_surcharge_percent:s.delivery_surcharge_percent,delivery_surcharge_label:s.delivery_surcharge_label})});state.catalog=await api("/api/admin/products");state.admin.printStatus=await api("/api/admin/print-status");toast("Integrações e preço por kg salvos");renderAdmin()}catch(error){toast(error.message);button.disabled=false}};
}
const integrationsStartAdmin=startAdmin;
startAdmin=async function(){await integrationsStartAdmin();if(state.admin.logged)api("/api/admin/integrations/status").then(result=>state.admin.integrationStatus=result).catch(()=>{})};
const integrationBindAdmin=bindAdmin;
bindAdmin=function(){integrationBindAdmin();document.querySelectorAll('[data-admin-view="integrations"]').forEach(button=>button.onclick=async()=>{state.admin.view="integrations";[state.catalog,state.admin.printStatus,state.admin.integrationStatus]=await Promise.all([api("/api/admin/products"),api("/api/admin/print-status"),api("/api/admin/integrations/status")]);renderAdmin()})};

/* Configurações gerais não devem mais carregar credenciais de integração. */
const integrationsSettingsView=settingsView;
settingsView=function(){return integrationsSettingsView().replace(/<section class="panel pedeai-panel">[\s\S]*?<\/section>(?=<div class="settings-save">)/,"")};
setupTableSettings=function(){
  const form=$("#settings-form"),s=state.catalog.settings||{};if(!form)return;
  if(!form.querySelector('[name="table_count"]'))form.insertAdjacentHTML("afterbegin",`<section class="panel table-settings"><div class="panel-head"><div><h2>Mesas e Destaques</h2><span class="muted">Defina mesas e quantidade de produtos em Destaques.</span></div><a class="secondary-btn" href="/mesas" target="_blank" rel="noopener noreferrer">Abrir telão</a></div><div class="settings-grid"><div class="field"><label>Quantidade de mesas</label><input type="number" name="table_count" min="0" max="200" value="${Number(s.table_count||0)}"></div><div class="field"><label>Produtos em Destaques</label><input type="number" name="featured_product_limit" min="1" max="30" value="${Number(s.featured_product_limit||15)}"></div></div></section>`);
  form.onsubmit=async event=>{event.preventDefault();const data=new FormData(form),button=form.querySelector(".primary-btn");button.disabled=true;try{await api("/api/admin/settings",{method:"PATCH",body:JSON.stringify({is_open:$("#store-open").classList.contains("on"),closing_time:data.get("closing_time"),minimum_order_cents:Math.max(0,Math.round(Number(String(data.get("minimum_order")).replace(",","."))*100)||0),delivery_eta:data.get("delivery_eta"),pickup_eta:data.get("pickup_eta"),phone:data.get("phone"),address:data.get("address"),table_count:Math.max(0,Math.min(200,Number(data.get("table_count"))||0)),featured_product_limit:Math.max(1,Math.min(30,Number(data.get("featured_product_limit"))||15)),waiter_fee_enabled:form.elements.waiter_fee_enabled.checked,waiter_fee_percent:Number(data.get("waiter_fee_percent")),delivery_neighborhood_fees:s.delivery_neighborhood_fees,delivery_surcharge_enabled:s.delivery_surcharge_enabled,delivery_surcharge_percent:s.delivery_surcharge_percent,delivery_surcharge_label:s.delivery_surcharge_label})});state.catalog=await api("/api/admin/products");toast("Configurações salvas");renderAdmin()}catch(error){toast(error.message);button.disabled=false}};
};
