// Promoções são opt-in: um produto só é exibido como promoção quando o proprietário ativar a opção e informar o valor promocional.
// A garrafinha de 300 ml possui sabor obrigatório e preço único, definido no produto.
queueMicrotask(()=>{
  const baseProductsViewWithFlavorPrices=productsView;
  productsView=function(){
    return baseProductsViewWithFlavorPrices().replace(/data-edit-product="1">Editar<\/button>/g,'data-edit-product="1">Editar sabores</button>').replace(/(<strong>Garrafinha trufada 300 ml<\/strong>)/,'$1<div class="product-flavor-note">Preço fixo: R$ 19,99 para todos os sabores</div>');
  };
  const baseOpenProductEditorWithFlavorPrices=openProductEditor;
  openProductEditor=function(id){
    baseOpenProductEditorWithFlavorPrices(id);
    if(Number(id)!==1)return;
    const panel=document.querySelector(".complement-editor");
    if(!panel)return;
    panel.classList.add("flavor-price-editor");
    panel.querySelector("strong").textContent="Sabores da garrafinha de 300 ml";
    panel.querySelector(".muted").textContent="O cliente escolhe 1 sabor. O preço é fixo: R$ 19,99, definido em Valor atual.";
    $("#add-product-complement").textContent="＋ Adicionar sabor";
    const relabelFlavorRows=()=>document.querySelectorAll(".admin-complement-row").forEach(row=>{
      const labels=row.querySelectorAll("label");
      if(labels[0])labels[0].textContent="Sabor";
      if(labels[1]){labels[1].textContent="Preço adicional";const price=row.querySelector("[data-complement-price]");if(price){price.value="0,00";price.disabled=true;}}
      if(labels[2]){labels[2].textContent="Quantidade";row.querySelector("[data-complement-max]").value="1";}
    });
    relabelFlavorRows();
    new MutationObserver(relabelFlavorRows).observe($("#product-complements"),{childList:true});
    $("#save-product").textContent="Salvar sabores";
  };
});
productsView=function(){const categories=state.catalog.categories||[...new Set(state.catalog.products.map(product=>product.category))],featuredLimit=Math.max(1,Math.min(30,Number(state.catalog.settings.featured_product_limit)||15));return `<section class="panel category-order-panel"><div class="panel-head"><div><h2>Ordem das categorias</h2><span class="muted">Use as setas para definir a ordem exibida no cardápio do cliente.</span></div></div><div class="category-order-list">${categories.map((category,index)=>`<div class="category-order-row"><b>${index+1}</b><span>${esc(category)}</span><button class="icon-btn" data-category-move="up" data-category-index="${index}" ${index===0?"disabled":""}>↑</button><button class="icon-btn" data-category-move="down" data-category-index="${index}" ${index===categories.length-1?"disabled":""}>↓</button></div>`).join("")}</div></section><section class="panel"><div class="panel-head"><div><h2>Cardápio</h2><span class="muted">Os ${featuredLimit} produtos mais pedidos aparecem automaticamente em Destaques.</span></div><button class="primary-btn" id="new-product">＋ Cadastrar produto</button></div><div class="product-admin-list">${state.catalog.products.map(p=>`<div class="product-admin-row"><img src="${esc(p.image_url)}" alt=""><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.description)}</div></div><div class="admin-category muted">${esc(p.category)}</div>${p.is_promo?`<div class="promo-admin-price"><small>Promoção</small><strong>${money(p.price_cents)}</strong></div>`:`<label class="admin-price-wrap"><span class="sr-only">Preço</span><input class="admin-price-input" data-price-id="${p.id}" inputmode="decimal" value="${(p.price_cents/100).toFixed(2).replace(".",",")}"></label>`}<div class="product-actions"><button class="secondary-btn compact" data-edit-product="${p.id}">Editar</button><button class="switch ${p.is_available?"on":""}" data-toggle-id="${p.id}" aria-label="Alternar disponibilidade"></button></div></div>`).join("")}</div></section>`}
productEditor=function(product){const p=product||{name:"",description:"",category:"",price_cents:0,old_price_cents:null,image_url:"",is_available:true,is_promo:false,complements:[]},cats=state.catalog.categories||[...new Set(state.catalog.products.map(x=>x.category))],originalPrice=p.old_price_cents?(p.old_price_cents/100).toFixed(2).replace(".",","):"";return `<div class="drawer-header"><button class="icon-btn" data-close>×</button><h2>${product?"Editar produto":"Cadastrar produto"}</h2></div><form class="drawer-content product-form" id="product-form"><div class="image-picker"><img id="product-preview" src="${esc(p.image_url||JW_LOGO)}" alt="Prévia da imagem"><label class="secondary-btn">Escolher imagem<input type="file" name="image" id="product-image" accept="image/jpeg,image/png,image/webp" hidden></label><small>JPG, PNG ou WebP • até 3 MB</small></div><div class="field"><label>Valor atual (R$)</label><input name="price" inputmode="decimal" required value="${p.price_cents?(p.price_cents/100).toFixed(2).replace(".",","):""}"></div><div class="field promotion-value-field" id="promotion-value-field" ${p.is_promo?"":"hidden"}><label>Valor original antes da promoção (R$)</label><input name="old_price" inputmode="decimal" value="${originalPrice}" placeholder="Ex.: 29,90"><small>Deve ser maior que o valor promocional.</small></div><div class="field"><label>Nome do produto</label><input name="name" maxlength="120" required value="${esc(p.name)}"></div><div class="field"><label>Descrição</label><textarea name="description" maxlength="500" placeholder="Ingredientes ou detalhes do produto">${esc(p.description)}</textarea></div><div class="field"><label>Categoria</label><input name="category" list="category-options" maxlength="80" required value="${esc(p.category)}"><datalist id="category-options">${cats.map(c=>`<option value="${esc(c)}">`).join("")}</datalist></div><section class="complement-editor"><div class="panel-head"><div><strong>Complementos deste produto</strong><div class="muted">Deixe vazio para bebidas ou produtos sem adicionais.</div></div><button type="button" class="secondary-btn compact" id="add-product-complement">＋ Adicionar</button></div><div id="product-complements">${(p.complements||[]).map(complementEditorRow).join("")}</div></section><div class="checks-grid"><label class="check-row"><input type="checkbox" name="is_available" ${p.is_available?"checked":""}><span>Disponível</span></label><label class="check-row"><input type="checkbox" name="is_promo" ${p.is_promo?"checked":""}><span>Ativar promoção</span></label></div></form><div class="drawer-footer"><button class="primary-btn full" id="save-product">${product?"Salvar alterações":"Cadastrar produto"}</button></div>`}
openProductEditor=function(id){const product=id?state.catalog.products.find(p=>p.id===id):null;layer(productEditor(product),"drawer admin-product-drawer");document.querySelector("[data-close]").onclick=closeLayer;$("#product-image").onchange=e=>{const file=e.target.files[0];if(file)$("#product-preview").src=URL.createObjectURL(file)};const promoToggle=$("[name=is_promo]"),promoField=$("#promotion-value-field");promoToggle.onchange=()=>{promoField.hidden=!promoToggle.checked;if(promoToggle.checked)promoField.querySelector("input").focus()};bindComplementEditor();$("#save-product").onclick=()=>saveProduct(product)}
saveProduct=async function(product){const form=$("#product-form");if(!form.reportValidity())return;const fd=new FormData(form),price=Math.round(Number(String(fd.get("price")).replace(",","."))*100),isPromo=form.elements.is_promo.checked,oldPrice=Math.round(Number(String(fd.get("old_price")||"").replace(",","."))*100);if(!Number.isFinite(price)||price<=0)return toast("Informe um valor válido");if(isPromo&&(!Number.isFinite(oldPrice)||oldPrice<=price))return toast("O valor original deve ser maior que o valor promocional");const complements=[...document.querySelectorAll(".admin-complement-row")].map(row=>({name:row.querySelector("[data-complement-name]").value.trim(),price_cents:Math.max(0,Math.round(Number(row.querySelector("[data-complement-price]").value.replace(",","."))*100)||0),max_quantity:Math.max(1,Math.min(20,Number(row.querySelector("[data-complement-max]").value)||1))})).filter(option=>option.name);fd.set("price_cents",String(price));fd.set("old_price_cents",isPromo?String(oldPrice):"");fd.set("complements_json",JSON.stringify(complements));for(const name of ["is_available","is_promo"])fd.set(name,form.elements[name].checked?"1":"0");const btn=$("#save-product");btn.disabled=true;try{await api(product?`/api/admin/products/${product.id}`:"/api/admin/products",{method:product?"PATCH":"POST",body:fd});state.catalog=await api("/api/admin/products");closeLayer();renderAdmin();toast(product?"Produto atualizado":"Produto cadastrado")}catch(e){toast(e.message);btn.disabled=false}}
